### ISSUE TITLE
Incorrect include for MPI4PY

### ISSUE THREAD

**Issue by kwryankrattiger** [SENSEI-insitu/SENSEI#150]
SENSEI is using the wrong MPI4PY header, should be `mpi4py/mpi4py.MPI_api.h` -> `mpi4py/mpi4py.h`

First reported here https://github.com/spack/spack/pull/46652#issuecomment-2383771214

```
build with py-mpi4py@4.0.0 gives:

In file included from /tmp/root/spack-stage/spack-stage-sensei-5.0.0-ljvl2tuclcjb2lclg6v4dwyaubi6d35a/spack-build-ljvl2tu/sensei/PythonAnalysisPYTHON_wrap.cxx:3326:
/tmp/root/spack-stage/spack-stage-sensei-5.0.0-ljvl2tuclcjb2lclg6v4dwyaubi6d35a/spack-src/sensei/PythonAnalysis.cxx:6:10: fatal error: mpi4py/mpi4py.MPI_api.h: No such file or directory
```
